### ISSUE TITLE
Not handling destructured args

### ISSUE THREAD

**Issue by yang** [pwlmaciejewski/coffeelint-variable-scope#10]
Just came across this:

```
$ cat mini.coffee
a = 1
b = 1
f = ({a,b}) ->
  a = 0

$ ./node_modules/.bin/coffeelint ./mini.coffee
  ✗ ./mini.coffee
     ✗ #1-4: Outer scope variable overwrite. a.

✗ Lint! » 1 error and 0 warnings in 1 file
```

**Comment by bchociej** [comment]
Similarly, destructuring array assignment does this:

```coffeescript
[a, ...] = thing()
```

```bash
$ node_modules/.bin/coffeelint -f coffeelint.json test/splatty-destruct.coffee
/home/ben/code/coffeelint-bundle/node_modules/coffeelint-variable-scope/index.js:113
              name = v.variable ? v.value.base.value : v.base.value;
                                                             ^

TypeError: Cannot read property 'value' of undefined
  at /home/ben/code/coffeelint-bundle/node_modules/coffeelint-variable-scope/index.js:113:62
  at /home/ben/code/coffeelint-bundle/node_modules/coffeelint/node_modules/coffee-script/lib/coffee-script/nodes.js:211:17
  at Block.exports.Base.Base.eachChild (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/node_modules/coffee-script/lib/coffee-script/nodes.js:199:17)
  at Block.exports.Base.Base.traverseChildren (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/node_modules/coffee-script/lib/coffee-script/nodes.js:209:19)
  at VariableScopeRule.module.exports.VariableScopeRule.nodeAssigns (/home/ben/code/coffeelint-bundle/node_modules/coffeelint-variable-scope/index.js:96:12)
  at VariableScopeRule.module.exports.VariableScopeRule.lintNode (/home/ben/code/coffeelint-bundle/node_modules/coffeelint-variable-scope/index.js:46:22)
  at VariableScopeRule.module.exports.VariableScopeRule.lintAST (/home/ben/code/coffeelint-bundle/node_modules/coffeelint-variable-scope/index.js:18:21)
  at ASTLinter.module.exports.ASTLinter.lint (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/lib/coffeelint.js:569:43)
  at Object.coffeelint.lint (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/lib/coffeelint.js:364:67)
  at ErrorReport.module.exports.ErrorReport.lint (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/lib/coffeelint.js:714:51)
  at lintFiles (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/lib/commandline.js:96:19)
  at Object.<anonymous> (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/lib/commandline.js:249:21)
  at Object.<anonymous> (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/lib/commandline.js:254:4)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/ben/code/coffeelint-bundle/node_modules/coffeelint/bin/coffeelint:34:5)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:475:10)
  at startup (node.js:117:18)
  at node.js:951:3
```
